% Copyright (C) 1995-2007 by Hiroshi Nakashima, Yasuki Saito and
%                            The Editorial Board of the IPSJ Journal
%
% ipsjpapers.cls 13-Mar-07 by Hiroshi Nakashima (ver 2.12)
% (revision history deleted)
% ipsjpapers.cls  1-Apr-96 by Hiroshi Nakashima (ver 2.00)

\ifx\pfmtname\undefined
	\NeedsTeXFormat{LaTeX2e}
\else
	\NeedsTeXFormat{pLaTeX2e}
\fi

\ProvidesClass{ipsjpapers}[2007/06/15 ver 2.12]
\input{ipsjpapers.sty}
\endinput
